fix: handle possible invalid keys and more valid ones
scrapy-plugins/scrapy-settings-log pull request #1
Opened 2024-03-07 12:54 UTC by aaneto

In some instances, the scrapy-settings-log extension can cause an error. For example, when the settings contain a class instance as a key, or a custom class.

This PR will attempt a "reasonable effort basis" conversion from these data types, while doing default conversion on unexpected values.

2024-03-20 20:01 UTC, curita requested changes
Thank you so much for these changes Adilson 🙏

They look great and it seems we should be addressing the encoding issues we've seen this way.

I left a couple of comments with further improvements, let me know your thoughts!

2024-03-20 20:01 UTC, curita commented on src/scrapy_settings_log/__init__.py
>          if isinstance(obj, BaseSettings):
**suggestion:** We can simplify the implementation a bit by dealing with non-composite values whenever possible and passing both the keyword and values through these functions.

I'm thinking something like this:

```python
from collections.abc import Iterable

class CustomEncoder(json.JSONEncoder):
    def default(self, obj):
        converted_obj = CustomEncoder.covert_settings_values(obj)
        return json.JSONEncoder.default(self, obj)

    @classmethod
    def convert_settings_values(cls, value):
        if isinstance(value, (str, int, float, bool)) or value is None:
            return value
        elif isinstance(value, BaseSettings) or isinstance(value, dict):
            return {cls.convert_settings_values(k): cls.convert_settings_values(v) for k, v in dict(value)}
        elif isinstance(value, Iterable):
            return [cls.convert_settings_values(v) for v in value]
        elif inspect.isclass(value):
	    return value.__name__
        else:
            logger.warn(f"Using __str__ for {key} as it cannot be encoded as JSON.")
            return str(value)
```

This implementation has some advantages:
* It supported decoding list-like recursively too
* It merges the implementation of the keyword and value decoding

2024-03-20 20:01 UTC, curita commented on src/scrapy_settings_log/__init__.py
> +    custom_encoder = CustomEncoder
**suggestion:** We should be able to overwrite or extend this class. I think we could add a setting like `"SCRAPY_SETTINGS_LOG_ENCODER_CLASS"`, with `"scrapy_settings_log.CustomEncoder"` as default, to give users the ability to overwrite it. Scrapy has a utility to load classes from strings, we can use it here.

2024-03-20 20:01 UTC, curita commented on src/scrapy_settings_log/__init__.py
> +        clean_settings = self.custom_encoder.clean_settings_dict(settings)
**question:** Do we need to call `self.custom_encoder.clean_settings_dict()` manually? Won't it be called by default when calling `json.dumps()`?

2024-03-20 20:01 UTC, curita commented on src/scrapy_settings_log/__init__.py
>  class CustomEncoder(json.JSONEncoder):
**todo:** We should add tests for this class to verify we encode the problematic cases correctly now.

2024-03-20 20:06 UTC, curita commented
I can't add more reviewers, but I'll tag a few folks who might be interested in checking these changes: @akhterwahab @muzaffaryousaf @VMRuiz @Gallaecio

2024-03-21 09:28 UTC, VMRuiz commented on src/scrapy_settings_log/__init__.py
>          if isinstance(obj, BaseSettings):
`isinstance(value, BaseSettings) or isinstance(value, dict):` can be simplify to  `isinstance(value, Mapping):`. 

```
        elif inspect.isclass(value):
	    return value.__name__
```
should return `str(value)` for a more descriptive output

2024-03-21 09:28 UTC, VMRuiz commented on src/scrapy_settings_log/__init__.py
> +    custom_encoder = CustomEncoder
Let's keep this for another PR

2024-03-21 09:29 UTC, VMRuiz requested changes
Could we add some tests?

2024-04-04 10:00 UTC, VMRuiz commented
Closed in favor of https://github.com/scrapy-plugins/scrapy-settings-log/pull/2 as I need to speed up this release

2024-04-04 10:00 UTC, closed without merging